Algoritmo "EXERCICIO A APOSTILA MANZANO"
// Disciplina   : [Lógica de Programação com Java Script]
// Professor   : Obaminha
// Descrição   : O algoritmo calcula o quadrado dos números inteiros
// de 15 ate 200! (função)
// Autor(a)    : Ariany
// Data atual  : 03/06/2023
Var
// Seção de Declarações das variáveis 
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i <- 15 ate 200 faca
      escreval(i*i)
   fimpara

Fimalgoritmo